repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system         # use your current venv (so deps are already installed)
        pass_filenames: false    # pytest decides what to run; don't pass changed files
        stages: [pre-push]