site_name: FastF1 Analytics
repo_url: https://github.com/kody-sherritze/fastf1_analytics
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.tabs.link
  palette:
    - scheme: slate
      primary: red
      accent: red

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Gallery: gallery.md
  - How it works: how-it-works.md
  - API:
      - Session Loader: api/session_loader.md
      - Plotting: api/plotting.md
      - fastf1_analytics: reference/fastf1_analytics.md